#!/bin/bash

if [ -n "$NEMO_SCRIPT_SELECTED_URIS" ]; then
    gksu -D "Éditer les fichiers en root" gedit $NEMO_SCRIPT_SELECTED_URIS
elif [ -n "$NAUTILUS_SCRIPT_SELECTED_URIS" ]; then
    gksu -D "Éditer les fichiers en root" gedit $NAUTILUS_SCRIPT_SELECTED_URIS
fi
